# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
before_install:
 - chmod +x Scripts/install.sh
 - chmod +x Scripts/build.sh
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh || true
- ls -lah
- ls -lah build/

deploy:
  provider: releases
  api_key: "$token"
  file: "./Build/linux/SchoolGameProject.exe"
  skip_cleanup: true
#  on:
#    tags: true
                                                                                                                                                                                                            

